# Generated by Django 2.2.5 on 2019-09-27 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ipm', '0002_pregador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('resumo', models.TextField(verbose_name='Resumo')),
                ('tags', models.CharField(choices=[('1', 'Avivamento'), ('2', 'Biografia'), ('3', 'Discipulado'), ('4', 'Evangelismo'), ('5', 'Família'), ('6', 'Ficção Cristã'), ('7', 'Geografía'), ('8', 'Gestão e Finanças'), ('9', 'História'), ('10', 'Igreja'), ('11', 'Libertação'), ('12', 'Liderança'), ('13', 'Oração'), ('14', 'Testemunho'), ('15', 'Vida Cristã')], max_length=30, verbose_name='Tags')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('media', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
