# Generated by Django 2.2.5 on 2019-09-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipm', '0004_cidade_igreja'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='capital',
            field=models.CharField(default=1, max_length=1, verbose_name='Capital'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.CharField(default=1, max_length=10, verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
